services:
  aneurism-iv:
    build: .
    ports:
      - "7777-7779:7777-7779/tcp"
      - "7777-7779:7777-7779/udp"

    tty: true
    restart: unless-stopped
    environment:
      - MAX_PLAYERS=50
      - BETA=
    stdin_open: true
    container_name: aniv-ds
    user: "1000:1000"
    volumes:
      - "./ds:/home/steam/aniv-ds/"
      - "./config:/home/steam/.config/unity3d/Vellocet/ANEURISM IV"
